import{a as C,S,i as a}from"./assets/vendor-DQvd0HNi.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();async function f(o,s){return(await C.get("https://pixabay.com/api/",{params:{key:"55127817-55120131a00f673dd7cbfbc42",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data}const g=document.querySelector(".gallery"),q=new S(".gallery a");function h(o){const s=o.map(e=>`<li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
      <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
      </a>
    <div class="gallery-description">
    <p>Likes ${e.likes}</p>
    <p>Views ${e.views}</p>
    <p>Comments ${e.comments}</p>
    <p>Downloads ${e.downloads}</p>
    </div>
    </li>`).join("");g.insertAdjacentHTML("beforeend",s),q.refresh()}function P(){g.innerHTML=""}const m=document.querySelector(".loader"),p=document.querySelector(".load-button");function y(){m.classList.add("is-visible")}function b(){m.classList.remove("is-visible")}function w(){p.classList.add("is-visible")}function l(){p.classList.remove("is-visible")}const L={user:document.querySelector(".form"),loadB:document.querySelector(".load-button")},v=15;let n="",i=1,u=0;L.user.addEventListener("submit",async o=>{if(o.preventDefault(),n=new FormData(o.target).get("search-text").trim(),!n){a.error({message:"Please enter a search query"});return}i=1,P(),l(),y();try{const e=await f(n,i);if(u=e.totalHits,!e.hits.length){a.error({message:"Sorry, there are no images matching your search query.",position:"topRight",backgroundColor:"#ef4040",messageColor:"white"});return}h(e.hits),i*v<u?w():(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#40afefff",messageColor:"white"}))}catch{a.error({message:"Something went wrong. Please try again later.",position:"topRight",backgroundColor:"#ef4040",messageColor:"white"})}finally{b()}});L.loadB.addEventListener("click",async()=>{i++,y(),l();try{const o=await f(n,i);h(o.hits),R(),i*v>=u?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#40afefff",messageColor:"white"})):w()}catch{a.error({message:"Something went wrong.",position:"topRight",backgroundColor:"#ef4040",messageColor:"white"})}finally{b()}});//!=========================================
function R(){const o=document.querySelector(".gallery-item:last-child");if(!o)return;const s=o.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
